version: "3.3"
services:
  postgres:
    image: "postgres:13.4-alpine"
    restart: always
    ports:
      - ${POSTGRES_PORT-5432}:5432
    environment:
      POSTGRES_USER: "default"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
